apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: platform
spec:
  replicas: 1         
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
        
          image: 442042534130.dkr.ecr.us-east-1.amazonaws.com/user-service:v1
          imagePullPolicy: Always    
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "48Mi"
              cpu: "25m"
            limits:
              memory: "96Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: platform
spec:
  selector:
    app: user-service
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP