apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 442042534130.dkr.ecr.us-east-1.amazonaws.com/product-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "48Mi"
              cpu: "25m"
            limits:
              memory: "96Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: platform
spec:
  selector:
    app: product-service
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP