apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ahsanch116/gitops-repo.git
    targetRevision: HEAD
    path: charts/microservice          # ← points to the Helm chart
    helm:
      valueFiles:
        - ../../values/user-service.yaml   # ← per-service values
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true